### PR TITLE
Cherry pick 1951 for 3-7 maintenance

### PR DESCRIPTION
**Pull request by samphippen**
@wbreeze can you confirm this is a correct cherry-pick?

### CODE REVIEW

**Comment by wbreeze** [comment]
I don't think you got what you want from the commit that changed [travis.yml](https://github.com/rspec/rspec-rails/pull/2004/commits/bf89116d6e9e423c9466a85f0f6b03031b5a6291)

**Comment by wbreeze** [comment]
It turns out that the version check was unnecessary. [PR#1965](https://github.com/rspec/rspec-rails/pull/1965) repairs that, but hasn't been reviewed.

**Comment by wbreeze** [comment]
This is cherry picking from PR #1951

**Comment by wbreeze** [comment]
Somehow the cherry-picking missed important changes in [have_http_status](https://github.com/rspec/rspec-rails/pull/2004/files#diff-0aea6f2f750998d0a72c1cffbf9475fd)

**Comment by wbreeze** [comment]
The test changed in more comprehensive ways, but might pass as you have it.

**Comment by JonRowe** [comment]
I usually just cherry pick the merge commits across manually @samphippen

**Comment by wbreeze** [comment]
Yes, of course. There's a merge commit, this one https://github.com/rspec/rspec-rails/commit/9bb089a174c3455c37d4579bc8e9424545d5d205 and immediately after that, one that updates the change log https://github.com/rspec/rspec-rails/commit/14357eb3047b97e308dac2fa8475f108c11573c5

Both on 22 February

**Comment by JonRowe** [comment]
Closing as stale, sorry this never got finished!

**Pull request closed without merging**
