### PR TITLE
Stop using webdrivers

### PR DESCRIPTION
**Pull request by jcoyne**
selenium-webdriver provides all that is needed now

### CODE REVIEW

**Comment by pirj** [comment]
Isn’t selenium-webdriver 4.10+ that is capable to use the selenium manager Ruby 3+ only?

We’re fixing build issues at the moment, and this is the major one. If you have a clear idea how to download drivers for Ruby 2.6, 2.7 and 3+, that will help a lot.

Please ignore Rails 7.1 and 7.0 builds, there’s at least some mailers failing spec.

**Comment by pirj** [comment]
3.1 and 3.0 fail because of this https://github.com/rails/rails/blob/1540cb381b4c78f1bcd7e081717a9e0a6706a9d8/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L73

**Comment by pirj** [comment]
https://github.com/rspec/rspec-rails/pull/2692

**Comment by JonRowe** [comment]
Bare in mind this branch supports Rails 6 as well as 7, and this file is about making a new rails app work on CI, so this probably needs at least a version switch around the rails version, as we are modifying a default app's Gemfile...

**Comment by JonRowe** [comment]
I didn't think this would work on 6.1 but it does, thus I'm going to merge it into #2692 thank you!

**Pull request merged**
