### PR TITLE
Fix variable name when generate scaffold with namespace & model-name

### LINKED ISSUE #2693: Wrong variable name when generate scaffold with namespace & model-name options
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.2.2
Rails version: 7.0.8
RSpec version: 3.12

## Observed behaviour

It wrong variable name with namepace prefix in the view specs, when is generated a namespace & model-name with scaffold.

```sh
$ rails g scaffold admin/user name:string --model-name=User
```

```ruby
# spec/views/admin/posts/show.html.slim_spec.rb
RSpec.describe "admin/posts/show", type: :view do
  before(:each) do
    assign(:admin_post, User.create!())
  end
...
end
```

```ruby
# spec/views/admin/posts/new.html.slim_spec.rb
RSpec.describe "admin/posts/new", type: :view do
  before(:each) do
    assign(:admin_post, User.new())
  end
...
end

```

```ruby
# spec/views/admin/posts/edit.html.slim_spec.rb
RSpec.describe "admin/posts/edit", type: :view do
  let(:admin_post) {
    User.create!()
  }

  before(:each) do
    assign(:admin_post, admin_post)
  end

  it "renders the edit admin_post form" do
    render

    assert_select "form[action=?][method=?]", admin_post_path(admin_post), "post" do
    end
end
```

## Expected behaviour

It is expected that the generated code is below.

```ruby
# spec/views/admin/posts/show.html.slim_spec.rb
RSpec.describe "admin/posts/show", type: :view do
  before(:each) do
    assign(:post, User.create!())
  end
...
end
```

```ruby
# spec/views/admin/posts/new.html.slim_spec.rb
RSpec.describe "admin/posts/new", type: :view do
  before(:each) do
    assign(:post, User.new())
  end
...
end

```

```ruby
# spec/views/admin/posts/edit.html.slim_spec.rb
RSpec.describe "admin/posts/edit", type: :view do
  let(:post) {
    User.create!()
  }

  before(:each) do
    assign(:post, post)
  end

  it "renders the edit admin_post form" do
    render

    assert_select "form[action=?][method=?]", admin_post_path(post), "post" do
    end
end
```

## Can you provide an example app?

https://github.com/taketo1113/rails-sample-rspec-rails/tree/view-spec-model-name

### PR DESCRIPTION
**Pull request by taketo1113**
Fixes #2693 

Fix variable name in view spec when generate scaffold with namespace & model-name.

### CODE REVIEW

**Comment by pirj** [comment]
Please hold on, we are working on ci fixes and adding 7.1 ci jobs.

**Comment by JonRowe** [comment]
:wave: Can you rebase this off of main which should now pass CI

**Comment by taketo1113** [comment]
@JonRowe Thanks to reply.
I have rebased and pass CI.

**Comment by JonRowe** [comment]
Released in 6.0.4 / 6.1.0

**Pull request merged**
