### PR TITLE
Updates from rspec-dev (2016-01-06)

### PR DESCRIPTION
**Pull request by myronmarston**
These are some updates, generated from rspec-dev's rake tasks.

### CODE REVIEW

**Comment by JonRowe** [comment]
Don't think this failure is related to the changes, @samphippen @cupakromer any ideas?

**Comment by samphippen** [comment]
I've literally no idea, it looks like it failed installing the debugger gem's native extensions. Maybe file an issue against their repo?

**Comment by yujinakayama** [comment]
In #1516 (for master) I removed `debugger` dep from the example app due to the build failure.

**Comment by samphippen** [comment]
Can we merge this now it's green?

**Comment by JonRowe** [comment]
Don't see why not!

**Pull request merged**
