### PR TITLE
Setup to run Rails 5 builds, and fix a few issues.

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by marcusg** [comment]
@JonRowe looks like the gemspec needs to be updated to allow Rails dependencies > 4.3

**Comment by lucianosousa** [comment]
you should update these 3 lines here
https://github.com/rspec/rspec-rails/blob/master/rspec-rails.gemspec#L28

it needs accept higher version than 4.3

**Comment by jasnow** [comment]
Once these changes are merged into master or a separate branch, I am willing to try them out on some repos that I have ported to Rails 5.

**Comment by JonRowe** [comment]
@jasnow this is already on a separate branch ;)

**Comment by jasnow** [comment]
@JonRowe -- Which branch - attempt_to_run_rails_5 or rails-5-support or something else?

**Comment by JonRowe** [comment]
`attempt_to_run_rails_5` as it says at the top of the PR

**Comment by jasnow** [comment]
oh - learned something today - THANKS

**Comment by JonRowe** [comment]
No worries :)

**Comment by samphippen** [comment]
@JonRowe Thanks for this. I just pushed a few more commits which fix up some more specs. I've been chatting with @cupakromer and we're going to push forward on top of this PR to get stuff up and working. From talking with @sgrif, we're going to have a rails branch called `5-0-stable` to build off sometime in december. Master should be relatively stable on the rails side atm.

**Comment by samphippen** [comment]
I've renamed this to Rails 5 support PR because I feel like it's the best effort we've got so far.

**Comment by JonRowe** [comment]
I'd recommend just merging this and going from there, this at least gets
the build running and pushes a few fixes out. We can officially support it
later on when your branches are ready.

**Comment by JonRowe** [comment]
I'd rather you didn't rename it, it's not intended to be a full support,
just enough to build off on master. Smaller PRs are easier to merge, I
would have merged it myself already except I was waiting for @cupakromers
sign off.

**Comment by samphippen** [comment]
Fair enough... I'll rebase it back to where it was and then merge it. It's LGTM.

**Comment by JonRowe** [comment]
Bah you've pushed commits already, can you unpick and open a separate
PR please Sam.

**Comment by samphippen** [comment]
@JonRowe I've just rebased this branch back to it's previous state. Should be good to merge on green?

**Comment by samphippen** [comment]
This is going to fail because travis can't install nokogiri 1.6.6.4 for some reason :( sorry @JonRowe.

**Comment by samphippen** [comment]
I'll see if I can work this out.

**Comment by samphippen** [comment]
This has already been dealt with in: https://github.com/rspec/rspec-rails/pull/1493 which I'll merge and rebase against.

**Comment by JonRowe** [comment]
:heart:

**Comment by lucianosousa** [comment]
yay!

**Pull request merged**
