### PR TITLE
Fix jruby-head

### PR DESCRIPTION
**Pull request by pirj**

### CODE REVIEW

**Comment by pirj** [comment]
Sent a pull request to fix the problem https://github.com/jruby/jruby/pull/6166

**Comment by benoittgt** [comment]
Can we change the strategy for jruby? Why "head"? I do not see a clear reason to use it at first sight https://github.com/rspec/rspec-rails/commit/c4e465d4cd84e973457c0e894f3c33a0ccf28dcd

**Comment by JonRowe** [comment]
I think because there isn't a recent version on travis?

**Comment by benoittgt** [comment]
> I think because there isn't a recent version on travis?

True. 😕
https://rubies.travis-ci.org/ last jruby release https://github.com/jruby/jruby/releases/tag/9.1.9.0

**Pull request closed without merging**
