### PR TITLE
Update gem description to include Rails 5.

### PR DESCRIPTION
**Pull request by benpickles**

### CODE REVIEW

**Comment by samphippen** [comment]
@myronmarston @JonRowe how do you feel about bumping to 3.5.1 for this and release?

**Comment by myronmarston** [comment]
I think it definitely makes sense to cherry-pick this to the 3-5-maintenance branch to be included in the next release, but it feels unnecessary to cut a release with just this.  This doesn't affect any functionality, after all -- it's basically just a glorified comment.

**Comment by samphippen** [comment]
@myronmarston that seems good. I'll do that :)

**Comment by samphippen** [comment]
Closing in favour of #1654

**Comment by myronmarston** [comment]
@samphippen this commit should be included in `master` and `3-5-maintenance`, so why not merge this one to get it in master?  Usually we just cherry-pick the commits to the maint branch instead of opening another PR (unless we are concerned about it causing a failing build in the branch).

**Comment by samphippen** [comment]
Ah right. Yes. Sorry, Misunderstood what you meant by cherry pick. I'll merge this one in now.

**Comment by samphippen** [comment]
@benpickles thanks for this! it's now merged into all the relevant RSpec branches :)

**Comment by benpickles** [comment]
My pleasure.

Thanks for maintaining such a great library, it's nice to watch development in the open.

**Pull request merged**
