### PR TITLE
Add a reproduction case for #2242

### PR DESCRIPTION
**Pull request by benoittgt**
Please do not merge. This is for testing purpose for #2242

### CODE REVIEW

**Comment by benoittgt** [comment]
We have a failures but this is unrelated. I will take a look. Otherwise we can see that we have one less error with the patch from #2242

**Comment by jrochkind** [comment]
Failing only on Rails6 (but oddly not on JRuby Rails6). 

Still feel free to let me know if it would be helpful if I made a standalone repro app (that passes with the code change, but fails without it, only on Rails6). 

This stuff definitely gets tricky, the Rails internals and how rspec tries to mimic them, and how they can differ in slightly different environments.

**Comment by benoittgt** [comment]
No no it's ok. I revert your patch to see that test fails.

Everything LGTM.

**Comment by benoittgt** [comment]
Closing. I push on 2242.

**Pull request closed without merging**
