### PR TITLE
Create controller generator for routing specs

### PR DESCRIPTION
**Pull request by 00dav00**
This PR covers #1160 and has been open instead of #1806 

This creates routing specs for controller generator

/cc @rspec/rspec

### CODE REVIEW

**Comment by 00dav00** [comment]
@JonRowe I forked the branch to my own repository since I no longer have writing permissions to the other one. I addressed your comments, could you take a look please?

BTW, I think the failing tests are not related to this PR, any ideas what could these could about?

[Test 1](https://travis-ci.org/rspec/rspec-rails/jobs/541741723) `Failure/Error: require 'rspec/rails'`
[Test 2](https://travis-ci.org/rspec/rspec-rails/jobs/541741727) `The command "script/run_build 2>&1" exited with 1.`
[Test 3](https://travis-ci.org/rspec/rspec-rails/jobs/541741787) `The command "script/run_build 2>&1" exited with 1.`

**Comment by benoittgt** [comment]
Thanks for this PR @00dav00 

What do you think about pointing to https://github.com/rspec/rspec-rails/tree/4-0-dev instead of master?

I don't see any clear path on failing CI. I reran the failing job. If you point to https://github.com/rspec/rspec-rails/tree/4-0-dev to build matrix is much smaller.

I think this change deserve to be in next release of rspec-rails 4.

**Comment by 00dav00** [comment]
Sure @benoittgt, let me rebase it against 4-0-dev

**Comment by 00dav00** [comment]
@benoittgt @JonRowe Done, this is now pointing to 4-0-dev :+1:

**Comment by 00dav00** [comment]
@benoittgt It's failing for a couple specs in Rails 6.0 in specs that are not related to the PR. The problem seems to be in some header info that are added in Rails 6.0
```
expect(response.content_type).to eq "application/json"

expected: "application/json"
         got: "application/json; charset=utf-8"
```

I don't think this related to the PR, but I can use a more flexible matcher to compare this if you think this should be changed int his PR

**Comment by benoittgt** [comment]
Failing CI on Rails 6. Is unrelated. I will submit a patch to fix 4-0-dev. :)

**Comment by benoittgt** [comment]
Hey. Can you rebase over 4-0-dev? I submited a patch

**Comment by 00dav00** [comment]
Done @benoittgt !
All green now :tada:

**Pull request merged**
