### PR TITLE
remove all spec views on destroy controller

### PR DESCRIPTION
**Pull request by Naokimi**
**Actions**:
1. `rails g controller Authors index show`
2. `rails d controller Authors` 

**Current**
_ON GENERATE_
Rails generates controller and view files
Rspec generates controller and view files
_ON DESTROY_
Rails destroys controller and view files
Rspec destroys only controller

**Proposal**
_ON DESTROY_
Rails destroys controller and view files
Rspec destroys controller and view files

### CODE REVIEW

**Comment by pirj** [comment]
Awesome! Can you please add specs for this change?

**Comment by Naokimi** [comment]
`run_generator %w[posts], behavior: :revoke` isn't working and I can't figure out why
they use it for rails: https://github.com/rails/rails/blob/main/railties/test/generators/task_generator_test.rb#L23

**Comment by Naokimi** [comment]
@pirj found a workaround, ready to be reviewed again

**Comment by benoittgt** [comment]
Hello @Naokimi  and thanks for you PR.

Tested locally and it is looks good to me.

Capture d’écran 2021-03-08 à 21 13 43

**Review by benoittgt — APPROVED** [review]

**Comment by JonRowe** [comment]
Do we have this problem with other generators? Do we want to ensure we're consistent?

**Comment by Naokimi** [comment]
seems like other generators work as intended
just controller one had a guard clause that would block expected behaviour

**Pull request merged**
