### PR TITLE
Rename filenames from travis to ci

### PR DESCRIPTION
**Pull request by Maroo-b**
This is a fix for https://github.com/rspec/rspec-rails/issues/2435

I tried to follow the approach used in this PR: https://github.com/rspec/rspec-dev/pull/254/files by renaming only filenames and leave the internal function names to have `travis` as a prefix (as it's used specifically for Travis)

### CODE REVIEW

**Comment by pirj** [comment]
Thanks!

I could find `script/after_update_travis_build.sh`/`script/before_update_travis_build.sh`. Wondering if they are used at all.

**Comment by Maroo-b** [comment]
@pirj I didn't find any usage of those files in this project and I wasn't sure if that's either a legacy code or it's used somehow by Travis lifecycle.

**Comment by JonRowe** [comment]
Those files are/were hooks for the build to run at various points, its possible they aren't used in this project anymore.

**Comment by Maroo-b** [comment]
@JonRowe thanks for the input, I updated the names of these script files as well.

**Comment by pirj** [comment]
Do you mind giving it a try and remove `script/{before,after}_update_*_build.sh`?

**Comment by Maroo-b** [comment]
In theory, it should be fine to remove those files, I'll update the PR

**Review by pirj — APPROVED** [review]
Thanks!

**Comment by Maroo-b** [comment]
Happy to help :)

**Pull request merged**
