### PR TITLE
Add Mailer suffix for rails 5

### PR DESCRIPTION
**Pull request by koenpunt**
This is the same fix as in the mailer template generator

### CODE REVIEW

**Comment by samphippen** [comment]
@koenpunt what was failing before this commit? What doesn't fail after this commit?

**Comment by koenpunt** [comment]
It's an extension on what you did here: https://github.com/rspec/rspec-rails/commit/7a13bf15a191add538c5293c18c7a8dd3fe96e12
So without this change, the mailer preview class wouldn't work because the mailer class without the `Mailer` suffix doesn't exist.

I don't believe there's a test for this file, but maybe there should be?

**Comment by samphippen** [comment]
@koenpunt if you have the time, it'd be great if we could get a spec for this.

**Comment by samphippen** [comment]
@koenpunt this was merged as part of #1573

**Comment by koenpunt** [comment]
:+1:

**Pull request closed without merging**
