### PR TITLE
Resolves issue #1044. Adding custom content types to feature, request…

### PR DESCRIPTION
**Pull request by jdax**
…, controller specs. Also adding code to fix a bundler issue (pull from tmp rails app gemfile).

### CODE REVIEW

**Comment by cupakromer** [comment]
Awesome! Thanks :blue_heart: I know that bunder issue was real pain. And the weird Rails header changes between 3 and 4 are pretty surprising. Thanks for taking the time to document all of that!

**Comment by JonRowe** [comment]
This PR changed the line endings incorrectly on the features files, does anyone feel like cleaning it up?

**Comment by cupakromer** [comment]
It's already been cleaned up.

**Comment by JonRowe** [comment]
:+1:

**Pull request merged**
