### PR TITLE
[WIP] Fix NoMethodError: render_views?

### PR DESCRIPTION
**Pull request by yujinakayama**

### CODE REVIEW

**Comment by aCandidMind** [comment]
My PR #1827 offers an approach to the error and makes this spec go green. Don't know if it's ideal that my PR is targeted at your PR branch.

**Comment by ayanko** [comment]
Any updates on this? It's pretty boring bug...

**Comment by tvanderpol** [comment]
This PR is a test-only description of the issue fixed in https://github.com/rspec/rspec-rails/pull/1831 as far as I can tell.

If the above PR fixed the issue and the tests in this PR aren't needed any longer, I think this could be closed.

**Comment by JonRowe** [comment]
Agree, closing

**Pull request closed without merging**
