### PR TITLE
Rake 12.3 cannot install on Ruby 1.9.3.

### PR DESCRIPTION
**Pull request by myronmarston**

### CODE REVIEW

**Comment by myronmarston** [comment]
This issue was exposed by the travis build on rspec/rspec-expectations#1034.

**Comment by myronmarston** [comment]
Can someone from @rspec/rspec review this?   The build failure doesn't seem related, FWIW.

**Comment by myronmarston** [comment]
Thanks, @yujinakayama. @samphippen / @JonRowe how do you feel about this being merged w/ a red build?

**Comment by samphippen** [comment]
@myronmarston I believe this red build is breaking due to the same reason as bundler 1.16.1 on rails: 
https://travis-ci.org/rails/rails/builds/319911098
https://github.com/bundler/bundler/pull/6202
https://travis-ci.org/rails/rails/jobs/319875431

can you try pinning the build to bundler `~> 1.15` and see if it fixes it?

**Comment by myronmarston** [comment]
> can you try pinning the build to bundler ~> 1.15 and see if it fixes it?

How do I do that?  I don't remember how and the feedback cycle on pushing changes to the rspec-rails build is sooooo slow.

And actually, rspec/rspec-expectations#1034 is going green now, so this no longer is necessary for what I'm doing there.  @samphippen, do you want to take this over?  Otherwise I'll probably close it.

**Comment by samphippen** [comment]
@myronmarston I got this :)

**Pull request closed without merging**
