### PR TITLE
Fix regression with stubbing ActiveRecord model classes.

### LINKED ISSUE #1394: allow no longer works with ActiveRecord classes
Known issue over at https://github.com/rspec/rspec-mocks, but I thought it might be useful to have a clone of https://github.com/rspec/rspec-mocks/issues/972 to flag this to anyone else seeing lots of failing specs when upgrading to 3.3.0.

### PR DESCRIPTION
**Pull request by myronmarston**
Fixes #1394.
See also rspec/rspec-mocks#972.

### CODE REVIEW

**Comment by cupakromer** [comment]
Beat me to too. Was writing the same thing currently. I'd like to tack on an acceptance spec as well. @myronmarston would it be alright for me to push it to this branch?

**Comment by myronmarston** [comment]
Please do!

**Comment by cupakromer** [comment]
BTW I did verify that without the fix the ["supports stubbing class methods on models"](https://github.com/rspec/rspec-rails/commit/811e1cbcd7#diff-bd8a29b8091c03ce2aff6b8acf6f18b6R4) spec fails with the original issue's error.

This LGTM :+1:

**Comment by myronmarston** [comment]
Great. I'll try to cut a release later today.

**Comment by JonRowe** [comment]
:green_heart:

**Pull request merged**
