### PR TITLE
Build updates

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by JonRowe** [comment]
This brings us inline with main, the failed builds are expected for 6.1

**Review by benoittgt — APPROVED** [review]
For the first error for 6.1. We need probably to do the same as https://github.com/rspec/rspec-rails/pull/2400/files#diff-cd9b3aaefde03e310efc31fece6cab46c2fc0a2e45a878a0357c749b0890d21dL17

**Comment by JonRowe** [comment]
@benoittgt can you pick just that change out of that PR and open another PR against the main branch? I want to introduce the changes in small doses

**Comment by benoittgt** [comment]
Yes 👍

**Pull request merged**
