### PR TITLE
Label Rspec as @private for docs, update other modules visibility

### PR DESCRIPTION
**Pull request by JonRowe**
This should remove the broken documentation links, which it does but it also labels everything under `RSpec` as private :/ This is for rspec/rspec.github.io#50...
screen shot 2015-10-20 at 21 52 04
screen shot 2015-10-20 at 21 52 10

### CODE REVIEW

**Comment by JonRowe** [comment]
See lsegal/yard#906

**Comment by JonRowe** [comment]
Ok, so it turns out YARD wasn't responsible for this entirely, our modules are actually mislabeled on master so we can just hide lowercase `Rspec` and it's ok, I went through all the docs and updated the visibility correctly. Needs a review @myronmarston @soulcutter @cupakromer

**Comment by myronmarston** [comment]
If this fixes the doc issue, LGTM.

**Comment by JonRowe** [comment]
@myronmarston it does for me with `yard --server`

**Comment by myronmarston** [comment]
> @myronmarston it does for me with yard --server

Have you tried generating the docs for rspec.info, though?  Would be nice to see it work for that since that's a different process.

**Comment by JonRowe** [comment]
Am I ok to merge this? I'd like to cherry pick it back to 3-3 so I can test doc regeneration

**Comment by myronmarston** [comment]
Merge away.

**Pull request merged**
