### PR TITLE
MISC #2161 - update EmptyTemplateHandler::call to support rails 6 tem…

### PR DESCRIPTION
**Pull request by feixionglee**
try to fix this issue https://github.com/rspec/rspec-rails/issues/2161

### CODE REVIEW

**Comment by benoittgt** [comment]
Hello @feixionglee 

Thanks for your contribution 👏 

We need a non regression test for this to be able to validate this fix.

If you are still working on this. Could you please change the PR to Draft mode? 

Thanks

**Comment by JonRowe** [comment]
Closing, duplicate of #2089

**Comment by feixionglee** [comment]
Thanks you guys, I do not notice this kind of fix has been merge to 4-0-dev branch, hope it can release soon 😄

**Comment by JonRowe** [comment]
This should be in `4.0.0.beta2`

**Pull request closed without merging**
