### PR TITLE
Singularize classes for feature names

### PR DESCRIPTION
**Pull request by dysnomian**
This PR addresses issue #1403 by singularizing the class and table names in the feature generators.

### CODE REVIEW

**Comment by JonRowe** [comment]
Do we not have tests for the generators?

**Comment by samphippen** [comment]
@dysnomian thanks for the pull request! Could you make it so that the singularization only happens on an option, rather than the default? I'm also *very* surprised that none of our tests failed here. @cupakromer my best guess is that it's because we use `rails g rspec:feature 'foos'` everywhere in our generator tests. Is that correct?

**Comment by cupakromer** [comment]
Yes, it looks like we simply have been passing plural options in our specs - so nothing failed. Clearly a gap in our specs testing that we "pluralized" stuff (>ლ). Also the change to the filename isn't covered by our specs either :grimacing: 

While this PR doesn't exactly singularize anything, it doesn't pluralize everything. :+1: If we can add a spec case for this that would be great.

In regards to the naming, I'm a little concerned that is a divergent change. The original use of `table_name` resulted in:

```console
$ bin/rails g rspec:feature warehouse::widget
      create  spec/features/warehouse/warehouse_widgets_spec.rb
```

With this change we now will get:

```console
$ bin/rails g rspec:feature warehouse::widget                
      create  spec/features/warehouse/warehouse::widget_spec.rb
```

**Comment by dysnomian** [comment]
@samphippen, @cupakromer: Thanks for the feedback! Next steps:
1. only singularize on a `--singularize` option
2. update tests so that they pass and fail appropriately on:
 * text
* spec filename
3. use `class_name` instead of `table_name` (that `::` was a surprising case I hadn't considered! :flushed: Good catch.)

Sound right?

**Comment by samphippen** [comment]
@dysnomian that sounds good to me.

**Comment by samphippen** [comment]
@dysnomian just wanted to check this was still something you're interested in working on? Let me know if you need any further help.

**Comment by dysnomian** [comment]
@samphippen Yeah, still interested!

**Comment by dysnomian** [comment]
Changes made. Any comments?

**Comment by samphippen** [comment]
This looks good. I'm going to locally add a changelog, and merge it down.

**Comment by samphippen** [comment]
@dysnomian it is my intention to merge this via #1508 when that PR passes CI.

**Comment by samphippen** [comment]
This was merged via #1508

**Pull request closed without merging**
