### PR TITLE
Reorganise matchers

### LINKED ISSUE #1488: have_enqueued_job not available by default in 3.4.0
When I try to use new matcher, I'm getting `You must pass an argument rather than a block to use the provided matcher (have enqueued job), or the matcher must implement supports_block_expectations?`
error.

After debugging it turns out that it's not autoloaded, I have to `include RSpec::Rails::Matchers`.

Any idea why is that?

### PR DESCRIPTION
**Pull request by JonRowe**
An attempt to fix #1488 by bringing the general matchers into "always included" but not the few very specific rails matchers.

### CODE REVIEW

**Comment by samphippen** [comment]
LGTM.

**Comment by JonRowe** [comment]
Bah, realised this is a semver violation, I'll rework it.

**Comment by samphippen** [comment]
@JonRowe isn't everything that you merged marked api privatE?

**Comment by JonRowe** [comment]
Yes apart from `RSpec::Rails::Matchers` which I'd removed some classes from.

**Comment by Senjai** [comment]
@JonRowe Thank you for poking at this. Much appreciated man.

**Pull request merged**
