### PR TITLE
Fixed Travis Run: Changed Gemfile to permit nokogiri 1.6.6.4 upgrade

### PR DESCRIPTION
**Pull request by jasnow**
Fixed Travis Run: Changed Gemfile to permit nokogiri 1.6.6.4 upgrade:
 * Before (6 red builds): https://travis-ci.org/rspec/rspec-rails/builds/91909748
 * After: (0 red builds): https://travis-ci.org/jasnow/rspec-rails/builds/92564244

### CODE REVIEW

**Comment by samphippen** [comment]
@jasnow Sick. Thanks.

**Comment by jasnow** [comment]
You're welcome.

**Comment by samphippen** [comment]
@jasnow this came literally as I was trying to work out what was going on to fix up another PR. So you've saved me loads of time. Seriously, thanks ^_^

**Comment by jasnow** [comment]
Seriously, you are welcome.

**Comment by JonRowe** [comment]
Versions `1.6.6.3` and `1.6.6.4` don't work on travis, now `1.6.6.5` is out we can drop that restriction entirely or we should have `gem 'nokogiri', ['~> 1.5', '< 1.6.6.3', '> 1.6.6.4']`.

**Comment by samphippen** [comment]
@JonRowe see #1497

**Pull request merged**
