### PR TITLE
Add gem version and semver stability badges to README

### PR DESCRIPTION
**Pull request by greysteil**
First of all, thanks for rspec-rails! I've used it on every Rails project I've ever worked on, and love it.

Would you be up for adding badges that display the current version on `rspec-rails`, and its semver stability? The former is pretty self-explanatory, the later is a new badge I've made that displays the percentage of rspec-rails users' CI runs that pass when updating rspec-rails between SemVer compatible versions. Data comes from Dependabot (disclosure: I built it).

I've also fixed the Code Climate badge in this PR (the URL must have changed on shields.io).

The badges now look like this:

[Build Status](http://travis-ci.org/rspec/rspec-rails) [Code Climate](https://codeclimate.com/github/rspec/rspec-rails) [Gem Version](http://badge.fury.io/rb/rspec-rails) [SemVer](https://dependabot.com/compatibility-score.html?dependency-name=rspec-rails&package-manager=bundler&version-scheme=semver)

### CODE REVIEW

**Comment by samphippen** [comment]
@greysteil I'm disinclined to add the "semver stability" badge as I can't independently verify that it actually works, or is in any way meaningful in the ruby programming language. The others we will need to consider.

**Comment by greysteil** [comment]
👍 - I've removed that one. It works pretty well, and picks out the 3.6.1 -> 3.7.0 break, for example, but I appreciate it needs more thought than the other two.

**Comment by samphippen** [comment]
LGTM

**Comment by greysteil** [comment]
Squashed into a single commit. Pretty innocuous change now, and you can confirm it renders [here](https://github.com/greysteil/rspec-rails/blob/616647cdf8f98a9c62fec1f7f6c638cf8297b116/README.md).

Separately, would love to talk you through the SemVer stability score if you're open to it?

**Comment by JonRowe** [comment]
If we want to have a coverage badge we need to setup coverage, it seems I'm not a member of the organisation, who initially configured RSpec on code climate?

**Comment by greysteil** [comment]
Just dug into the Code Climate issue. Looks like [this commit](https://github.com/rspec/rspec-rails/commit/c1472545d4a84f11e42ba0607aa47575b4d0481d#diff-04c6e90faac2675aa89e2176d2eec7d8) switched us to shields.io endpoint that is no longer supported, but the original URL still works. I've updated the badge accordingly:

[Code Climate](https://codeclimate.com/github/rspec/rspec-rails)

**Comment by olleolleolle** [comment]
@greysteil Could you rebase your changes? They're neat.

**Comment by samphippen** [comment]
@JonRowe I'm happy to merge this on green if you are.

**Comment by JonRowe** [comment]
I'm happy if the builds green

**Comment by greysteil** [comment]
Build is going to be 🔴 without https://github.com/rspec/rspec-rails/pull/2051.

**Comment by samphippen** [comment]
@greysteil let's rebase this now that the rubygems fix is merged.

**Comment by JonRowe** [comment]
❤️

**Pull request merged**
