### PR TITLE
custom resolver support

### PR DESCRIPTION
**Pull request by ahorek**
fixes https://github.com/rspec/rspec-rails/issues/1841

### CODE REVIEW

**Comment by JonRowe** [comment]
Thanks for trying to tackle this @ahorek could you please add a spec that shows what this fixes.

**Comment by JonRowe** [comment]
Thanks, @samphippen are you happy to merge this without getting master green first? Or should I hold off until master is all green, get this rebased and double check it passes?

**Comment by hogelog** [comment]
What status this PR?
I hope that this fix will be merged.

**Comment by ahorek** [comment]
done

**Pull request merged**
