### PR TITLE
Rails 52 improvements

### PR DESCRIPTION
**Pull request by JonRowe**
Add missing travis builds for 5.2.0 and improve an error message formatting post #1959

### CODE REVIEW

**Comment by samphippen** [comment]
@JonRowe this is likely red because it's not aligned with the patches in #1959. May want to look there.

**Comment by JonRowe** [comment]
@samphippen I made sure those changes where in, the red build were flakes

**Comment by JonRowe** [comment]
Merging as green

**Comment by annacruz** [comment]
Hey, when we gonna have a new release with these improvements

**Comment by JonRowe** [comment]
@annacruz this PR was mostly focused on improving our CI for Rails 5.2, theres a minor change to an error message and will be released in the next minor release.

**Pull request merged**
