### PR TITLE
Check if TestCase responds to the fixture_path setter

### PR DESCRIPTION
**Pull request by koenpunt**
The existence of the getter doesn't mean there's also a setter, so this resulted in failures like the following:

```
1) Admin::CollectionsController POST #create creates a record
     Failure/Error: banner_image: fixture_file_upload('alpaca.jpg', 'image/jpg')

     NoMethodError:
       undefined method `fixture_path=' for ActionController::TestCase:Class
       Did you mean?  fixture_path
```

### CODE REVIEW

**Comment by benoittgt** [comment]
Do you think it is possible to add a test?

**Comment by koenpunt** [comment]
I think so, will have a look tonight.

**Comment by JonRowe** [comment]
Are you seeing an issue from this @koenpunt? I think this method is always available isn't it?

**Comment by koenpunt** [comment]
Yeah I am, `fixture_file_upload` method doesn't work in my Rails 6 application

**Comment by JonRowe** [comment]
In that case we'd definitely like an integration spec for this so we can catch such problems in future :joy:

**Comment by benoittgt** [comment]
@koenpunt, if you need any help feel free to ask. I will be happy to help you.

**Comment by benoittgt** [comment]
Little bump on this one. Still available if you need help @koenpunt.

**Comment by koenpunt** [comment]
Yes, sorry, just started a new job so didn't really had time to take a look at this again. Will try to get back to this ASAP.

**Comment by koenpunt** [comment]
I've now added a test which I hoped was going to fail without my changes, but that isn't the case. Any pointers for how I could try to implement the test differently?

**Comment by koenpunt** [comment]
After some further investigation I realised that I actually added the `fixture_path` method to `ActionDispatch::TestProcess` to allow usage of `fixture_file_upload` from FactoryBot factories. But I didn't implement the setter, so this caused `rspec-rails` to raise the `NoMethodError`.

I've now changed my implementation to not modify `ActionDispatch::TestProcess`, but instead monkey patch the `fixture_file_upload` method into FactoryBot, which solves the issue.

That said, I still think the `respond_to?(:fixture_path)` isn't correct, because it checks the getter, but then uses the setter.

Should I create a test where I add the `fixture_path` method, to demonstrate the failure?

**Comment by JonRowe** [comment]
Closed by #2370

**Pull request closed without merging**
