### PR TITLE
Adds keywords arguments in requests for controller specs

### PR DESCRIPTION
**Pull request by diogobenica**
Without the keyword in arguments when making a request in specs, Rails will print this warning:

```
DEPRECATION WARNING: ActionController::TestCase HTTP request methods will accept only
keyword arguments in future Rails versions.

examples:

get :show, params: { id: 1 }, session: { user_id: 1 }
process :update, method: :post, params: { id: 1 }
```

### CODE REVIEW

**Comment by samphippen** [comment]
@diogobenica can you rebase this against RSpec master?

**Comment by diogobenica** [comment]
@samphippen Sure! A rebase against your master. Is it correct now?

**Comment by JonRowe** [comment]
Hi @diogobenica what @samphippen  meant was, could you reopen this pr against `master`, we're looking to see `b3a2d2e` against master, and not anything else :)

**Comment by diogobenica** [comment]
@JonRowe Oh, sorry for that. The new pr is the #1603

**Pull request closed without merging**
