### PR TITLE
Prevent Rails 3.2.22.1 on Ruby 1.8.7

### PR DESCRIPTION
**Pull request by JonRowe**
Assuming this works it'll fix our builds elsewhere and improves upon @samphippen's quick travis fix :)

### CODE REVIEW

**Comment by JonRowe** [comment]
@samphippen ready for review

**Comment by samphippen** [comment]
@JonRowe this LGTM, do you think it wants a changelog entry?

**Comment by JonRowe** [comment]
Hmm, I'm on the fence it's mostly internal but it will prevent 1.8.7 from installing that version of Rails so maybe?

**Comment by samphippen** [comment]
it's marginally user facing, so adding a changelog entry can't hurt imo.

**Comment by JonRowe** [comment]
Done

**Pull request merged**
