### PR TITLE
Don't swallow exceptions for flow control.  fixes #1656

### PR DESCRIPTION
**Pull request by betesh**
See discussion on #1656

### CODE REVIEW

**Comment by myronmarston** [comment]
LGTM.

I wonder if there are any other places where we use an exception approach that could switch to a version check approach?

**Comment by betesh** [comment]
Can we get this released as 3.5.1?  That would allow me to use it with rspec 3.5.0

**Comment by myronmarston** [comment]
> I believe @myronmarston is planning a release of all the gems shortly, would you mind waiting a day or so? We like to bundle together a few fixes at a time :)

I released rspec-core 3.5.1 last night, and didn't have any more releases planned. No need to wait for this.

**Comment by JonRowe** [comment]
My mistake, I assumed we were bumping them all, I can handle the release if you'd like?

**Comment by myronmarston** [comment]
There was nothing new to release in the others, and I usually release patch versions freely when needed.

> I can handle the release if you'd like?

Go for it!

**Comment by betesh** [comment]
Thank you!

**Pull request merged**
