### PR TITLE
Use keyword args for HTTP methods in controller specs only on Rails 5

### LINKED ISSUE #1669: Scaffold generator generates invalid controller specs on versions prior to Rails 5
In #1603, we made scaffold generator to generate controller specs with HTTP request method (`#get`, `#post`, etc.) with keyword arguments:

``` diff
- post '/books', { book: { title: 'Foo' } }
+ post '/books', params: { book: { title: 'Foo' } }
```

... regardless of the current project's Rails version.

However the keyword arguments are actually supported only on Rails 5 (https://github.com/rails/rails/pull/18323). The CI in #1603 was passing because [they were skipped](https://github.com/rspec/rspec-rails/blob/v3.5.1/lib/generators/rspec/scaffold/templates/controller_spec.rb#L27-L33).

### PR DESCRIPTION
**Pull request by yujinakayama**
This closes #1669.

### CODE REVIEW

**Comment by JonRowe** [comment]
These aren't keyword arguments tho, they're keyword argument on Rails 5, but new style hash access on Rails 4, I'm still unsure why it breaks and this doesn't fix the fact that specs don't pick it up...

**Comment by yujinakayama** [comment]
Should we replace the `skip` in the spec with empty hash?

```diff
  let(:valid_attributes) {
-   skip("Add a hash of attributes valid for your model")
+   {}
  }
```

**Comment by JonRowe** [comment]
I tried that in #1680, (basically we don't want to remove them from peoples scaffolded specs, but we do want them to run in our specs) but it passes and I'm not sure it's working correctly

**Comment by yujinakayama** [comment]
It seems that the scaffold specs are not executed in cukes since they're always removed before each scenario.

https://github.com/rspec/rspec-rails/blob/2175c72f42ebd40c946ccc45fe3a2ad0caa8df6f/features/support/env.rb#L37-L44

**Comment by mrageh** [comment]
@yujinakayama and @JonRowe I think we should merge this PR, because in Rails 5 HTTP request methods use keyword args to process requests. Whereas any version below Rails 5 uses does not use keyword args. That means our scaffold generator will produce invalid controller specs.

For more context please refer to this [PR](https://github.com/rails/rails/pull/18323/).

**Comment by JonRowe** [comment]
@mrageh as per my earlier comments this shouldn't be merged, Rails 5 swapped option hashes for keyword args, the api is supposed to be compatible without any changes to the user

**Comment by JonRowe** [comment]
@mrageh However if you'd like to work on getting our generated specs being tested as part of the build I'd welcome the help in a seperate PR.

**Comment by yujinakayama** [comment]
@JonRowe

> the api is supposed to be compatible without any changes to the user

No, `get '/', params: {}` does not work on Rails 4.2. Try the reproducible example in https://github.com/rspec/rspec-rails/issues/1669#issuecomment-239619487.

**Comment by mrageh** [comment]
@JonRowe I may have missed something, but I'm fairly certain the Rails 5 api change is not backwards compatible. Can you send me some docs/github discussion anything that says otherwise?

**Comment by yujinakayama** [comment]
This should be rebased once https://github.com/rspec/rspec-rails/pull/1680 is merged.

**Pull request merged**
